Feature/create message script
jigintern/online-2024-e pull request #28
Opened 2024-09-04 00:45 UTC by andnotand

new branch

2024-09-04 01:22 UTC, Ryo-7 requested changes
スクリプト追加ありがとうございます。

ちゃんと動作していて一気にアプリっぽくなっていい感じです。 👍 

コードを書く上でちょっと気になるところがあるので修正お願いします 🙇 
コメントつけてなくても同じような修正箇所がいくつかあるので全体をざっと確認してみて欲しいです。

2024-09-04 01:22 UTC, Ryo-7 commented on public/script.js
> +    var buttonstyle = window.getComputedStyle(document.getElementById('button'), '');
```suggestion
    const buttonstyle = window.getComputedStyle(document.getElementById('button'), '');
```

javascriptでvarは非推奨になってます。
変数はletを使って欲しいし、今回は宣言後に書き換えないと思うので constで良いかなと思いました。

2024-09-04 01:22 UTC, Ryo-7 commented on public/script.js
> +    const width = buttonstyle.getPropertyValue('width');
エディタでみると、この変数は使ってなさそうです。
使ってない変数はバグの原因になるので、消しておくと良いと思います。

2024-09-04 01:22 UTC, Ryo-7 commented on public/script.js
> +            console.log(response);
これはデバッグ用の `console.log`だと思うので、消しておきましょう

他にもコメントアウトしてる不要なコードは削除しておくと、全体の行数が減ってみやすくなります。

今は使わないけど前使ってて、いつか使うかもしれないというコードはgitのコミット上に載るので、そこから引っ張り出せるという点でも、基本的にコードはコメントアウトではなく削除でいいと思います

2024-09-04 01:22 UTC, Ryo-7 commented on public/script.js
> +    const b_text = text;//クリックしたボタンの文字
```suggestion
    const selectedCocktailMessage = text;//クリックしたボタンの文字
```
基本的に、javascriptの変数はlowerCamelCaseで書きます。
また、b_textだと何の変数か、将来の自分を含め分からなくなると思うので上記のようなのはどうでしょうか？ 🤔

2024-09-04 01:22 UTC, Ryo-7 commented on src/components/CreateMessageSelect.tsx
> +            <a href="/create/check">確認</a>
ここは僕の考慮ミスなんですが、今回のPRに不必要な変更が入ってしまっているので修正して欲しいです。 🙇

2024-09-04 01:22 UTC, Ryo-7 commented on src/components/CreateMessageSelect.tsx
> +    border-radius: 0.5rem;
この辺も不要な変更が入ってしまった気がします 🙇

2024-09-04 01:22 UTC, Ryo-7 commented on src/components/CreateMessageSelect.tsx
> +export function CreateMessageSelect() {
ここも不要な気がします 🙇

2024-09-04 01:36 UTC, yui-szk commented on public/script.js
> +window.addEventListener('load', (event) => {
引数の`event`は使用してなさそうなので、削除してもいいかもしれません

2024-09-04 01:39 UTC, 5ouma requested changes

2024-09-04 01:39 UTC, 5ouma commented on public/script.js
> +//tmp_list = ['apple', 'orange', 'grape', 'strawberry', 'apples'];//テスト用
Prettier等でコードをフォーマットしておくといいかも
インデントの数や波括弧前後のスペース等

2024-09-04 01:39 UTC, 5ouma commented on public/script.js
> +    }else if(document.getElementById("c_button").childElementCount >= 4){//配列の要素で判定
4つまでは許容するはず？

```suggestion
    }else if(document.getElementById("c_button").childElementCount > 4){//配列の要素で判定
```

2024-09-04 01:39 UTC, 5ouma commented on public/script.js
> +        }
三項演算子を使うと綺麗になるかも

```suggestion
        li.style.display = text2.includes(search_kekka) ? "" : "none";
```

2024-09-04 01:39 UTC, 5ouma commented on public/script.js
> +    }else{
`//nothing`があるのであれば、以下に変えるといいかも

```suggestion
    if (document.getElementById("c_button").childElementCount >= 4) {
        alert("これ以上言葉を追加できません");
    } else if (!created_sentence.includes(b_text)) {
```

2024-09-04 01:39 UTC, 5ouma commented on public/script.js
> +});
この`addEventListner`は何もしていない？

2024-09-04 01:43 UTC, yui-szk commented on public/script.js
> +            //console.log("created_sentence:" + created_sentence);成功
必要ないコメントは削除しましょう

2024-09-04 01:43 UTC, yui-szk commented on public/script.js
> +            //console.log(textContent); // クリックされた <li> 要素のテキストを表示
必要ないコメントは削除しましょう

2024-09-04 01:43 UTC, yui-szk commented on public/script.js
> +        //console.log(text2);//for test
必要ないコメントは削除しましょう

2024-09-04 01:44 UTC, yui-szk commented on public/script.js
> +        //console.log(created_sentence);//fortest
必要ないコメントは削除しましょう

2024-09-04 01:44 UTC, yui-szk commented on public/script.js
> +    //console.log(b_text);
必要ないコメントは削除しましょう

2024-09-04 01:53 UTC, yui-szk commented on public/script.js
> +document.addEventListener('DOMContentLoaded', function() {
```suggestion
document.addEventListener('DOMContentLoaded', () => {
```

2024-09-04 01:58 UTC, yui-szk commented on public/script.js
> +//tmp_list = ['apple', 'orange', 'grape', 'strawberry', 'apples'];//テスト用
このコメントも要らなそう

2024-09-04 02:03 UTC, yui-szk commented on public/script.js
> +});
私も何してるかわからなかった...

2024-09-04 04:27 UTC, yui-szk commented on public/share.js
作業内容が異なる場合はブランチを変更して作業してください

2024-09-04 04:27 UTC, yui-szk commented on src/components/CreateMessageCheck.tsx
> +
不必要な差分は出ないようにしてほしい

2024-09-04 05:29 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
> +            */}
不要なコメントは削除をー

2024-09-04 05:29 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
> +          {/*<button id="kennsaku_result">*/}
コメント削除

2024-09-04 05:30 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
> +          {/*</button>*/}
コメント削除

2024-09-04 05:32 UTC, Ryo-7 commented
ここだけ検索窓が切れてるのが気になりました。
サクッと直せそうなら修正コミットを積んでもらって、厳しそうなら別タスクを切りましょう
![スクリーンショット 2024-09-04 14 31 48](https://github.com/user-attachments/assets/a71eb5c9-1e91-47cb-8790-3c9f52aedc72)

2024-09-04 05:39 UTC, Ryo-7 submitted a review, later dismissed
動作に問題なさそう

LGTM 👍 

---
コメントを残す癖はめっちゃ大事です。

なんでも残せばいいってものじゃないのが難しいところですが、初見だとこのコードわからんだろうなってところに書くようにすると良いです。

次のPRはちょっとだけ意識してもらえると、良いコードになって最高だと思います 👍

2024-09-04 05:41 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
>                  <span class="material-symbols-outlined">search</span>
```suggestion
              <button type="submit">
                <span class="material-symbols-outlined">search</span>
              </button>
```
スタイルがずれているので修正お願いします

ボタンを押すと検索リセットされるので、後でアイコン修正するかもしれない

2024-09-04 06:21 UTC, yui-szk submitted a review, later dismissed
LGTM！

2024-09-04 06:39 UTC, 5ouma requested changes

2024-09-04 06:39 UTC, 5ouma commented on src/components/CreateMessageSelect.tsx
> +export function CreateMessageSelect() {
元に戻した方がよさそう

2024-09-04 06:39 UTC, 5ouma commented on src/components/CreateMessageSelect.tsx
> +            </ul>
頭に空白が入ってます

2024-09-04 06:39 UTC, 5ouma commented on public/script.js
> +});
[CreateMessageSelect.tsx](https://github.com/jigintern/online-2024-e/blob/c7c44feb1051b7f589409a507945dc20159e9e60/src/components/CreateMessageSelect.tsx)を下に置き換えると、APIから取ってきたデータを表示できるのですが…

```tsx
import { hc } from "@hono/hono/client";
import { css } from "@hono/hono/css";

import { WithHTML } from "../layout/WithHTML.tsx";
import { API } from "../api/mod.ts";
import { Cocktail } from "../api/utils/types.ts";

const client = hc<API>("http://0.0.0.0:8000/api");
const getAllCocktails = async (): Promise<Cocktail[]> => {
  const res = await client.cocktail.all.$get();
  if (!res.ok) throw new Error(await res.text());
  return await res.json();
};

const selectedStyle = css`
  height: 24vh;
  list-style: none;
  margin-top: 1.5rem;

  li {
    display: grid;
    grid-template-columns: 3fr 1fr;
    background-color: var(--color-base);
    font-size: 1rem;
    color: var(--color-main);
    padding: 0.25rem 0.75rem;
    margin: 0.5rem 0;
    border-radius: 2rem;
    align-items: center;

    button {
      justify-self: end;
      border: none;
      background-color: var(--color-base);
    }
  }
`;

const wordListContainerStyle = css`
  background-color: var(--color-base);
  border-radius: 1.25rem;

  form {
    display: flex;
    padding: 1rem;

    input {
      background-color: var(--color-main);
      color: var(--color-white);
      font-size: 1rem;
      width: 100%;
      border-radius: 0.5rem 0 0 0.5rem;
      padding: 0.75rem;
      border: none;
      outline: none;
    }

    button {
      border: none;
      background-color: var(--color-main);
      color: var(--color-white);
      border-radius: 0 0.5rem 0.5rem 0;
      padding-right: 0.5rem;
    }
  }
`;

const wordListStyle = css`
  list-style: none;
  color: var(--color-main);
  height: calc(100vh - 24vh - 9.25rem);
  overflow-y: scroll;

  li {
    display: grid;
    grid-template-columns: 5fr 2fr;
    font-size: 1rem;
    align-items: center;
    padding: 1rem;
    padding-left: 1.5rem;
    border-top: solid 1px var(--color-stroke);

    small {
      color: #7c7c7c;
      font-size: 0.75rem;
    }
  }
`;

const checkLinkStyle = css`
  position: absolute;
  bottom: -1.25rem;
  left: 50%;
  transform: translateX(-50%);

  a {
    background-color: var(--color-accent);
    width: 5rem;
    height: 5rem;
    border-radius: 100%;
    color: var(--color-white);
    text-decoration: none;
    font-size: 1.25rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }
`;

/**
 * メッセージを選択する画面を返す関数
 */

export const CreateMessageSelect = async () => {
  return (
    <WithHTML>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
      />
      <div>
        <div>
          <ul class={selectedStyle}>
            <li>
              あなたを守りたい
              <button>
                <span class="material-symbols-outlined">close</span>
              </button>
            </li>
            <li>
              いつも2人で
              <button>
                <span class="material-symbols-outlined">close</span>
              </button>
            </li>
          </ul>
        </div>
        <div class={wordListContainerStyle}>
          <div>
            <form action="">
              <input type="text" />
              <button type="submit">
                <span class="material-symbols-outlined">search</span>
              </button>
            </form>
          </div>
          <ul class={wordListStyle}>
            {(await getAllCocktails()).map((cocktail: Cocktail) => (
              <li>
                {cocktail.word}
                <small>{cocktail.name}</small>
              </li>
            ))}
          </ul>
          <div class={checkLinkStyle}>
            <a href="./check">確認</a>
          </div>
        </div>
      </div>
    </WithHTML>
  );
};
```

2024-09-04 06:39 UTC, 5ouma commented on public/script.js
> +let created_sentence = [];
Prettier等でコードをフォーマットしておくといいかも
インデントの数や波括弧前後のスペース等

2024-09-04 07:12 UTC, Ryo-7 commented on public/script.js
> +});
`.tsx`で書いた方が良さそうなので、@5ouma にこの部分の変更をお願いします。
ただ、このPRを入れないと辛いと思うので、このPRをマージした後で別PRとして出して欲しいです  🙏

2024-09-05 00:44 UTC, 5ouma submitted a review, later dismissed

2024-09-05 01:25 UTC, Ryo-7 submitted a review, later dismissed
動作するのとCIが通っているのでLGTM

細かい気になるところは、最悪後で僕が直します

2024-09-05 01:27 UTC, 5ouma requested changes

2024-09-05 01:27 UTC, 5ouma commented on public/share.js
空ファイル？

2024-09-05 01:27 UTC, 5ouma commented on src/components/CreateMessageSelect.tsx
> +//import {buttonclick, kennsaku_show} from "../../public/script.js"
これは消しましょう

2024-09-05 01:27 UTC, 5ouma commented on src/components/CreateMessageCheck.tsx
> -
元に戻した方がよさそう？

2024-09-05 01:31 UTC, yui-szk requested changes

2024-09-05 01:31 UTC, yui-szk commented on src/components/CreateMessageCheck.tsx
> +
他機能の実装なので、入れないでほしいな...

送る、のボタンは既にあるから、要らない気もする

2024-09-05 01:31 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
> +//import {buttonclick, kennsaku_show} from "../../public/script.js"
使わないやつは消してほしいな...

2024-09-05 01:31 UTC, yui-szk commented on src/components/CreateMessageSelect.tsx
> + * 作成するメッセージを選択する画面を返す関数
変更されてるので直してほしいです

2024-09-05 01:40 UTC, yui-szk approved these changes, later dismissed

2024-09-05 01:50 UTC, Ryo-7 submitted a review, later dismissed
動作する、不要なファイルはないことを確認

LGTM 👍

2024-09-05 01:56 UTC, 5ouma requested changes

2024-09-05 01:56 UTC, 5ouma commented on public/script.js
> +      tmp = [];
変数宣言を明示した方がよさそう

2024-09-05 01:56 UTC, 5ouma commented on src/components/CreateMessageSelect.tsx
> +          <ul class={selectedStyle} id="c_button"></ul>
`c_button`だと何のボタンが分かりづらいね

2024-09-05 01:56 UTC, 5ouma commented on public/script.js
> +    let text2 = "";
`text1`が無いので`text`で良いのでは

2024-09-05 02:12 UTC, 5ouma approved these changes

2024-09-05 02:14 UTC, yui-szk approved these changes

2024-09-05 02:15 UTC, merged